

#   pod install --verbose --no-repo-update
#
#   pod update --verbose --no-repo-update


platform :ios, "8.0"

target 'WTWeiBoBaseDemo' do


    pod 'AFNetworking', '~> 3.1.0'
    pod 'WMPageController', '~> 2.5.0'


end
